# Auto-generated by CI bump-version workflow. Do not edit manually.
__version__ = "0.1.33"
__commit__ = "a005c86b79ec01ee1313c2d4bcc166ffced08b8c"
__commit_message__ = "Merge branch 'main' of https://github.com/aviadr1/figmaclaw"
__pr__ = None
