# Auto-generated by CI bump-version workflow. Do not edit manually.
__version__ = "0.1.81"
__commit__ = "9aa9435a78717f1d77092487e49baea8936bd254"
__commit_message__ = "Merge branch 'main' of https://github.com/aviadr1/figmaclaw"
__pr__ = None
