#!/usr/bin/env python3
"""Bump figmaclaw patch version and write package/plugin metadata."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


def _bump_patch(version: str) -> str:
    parts = version.split(".")
    if len(parts) != 3:
        raise RuntimeError(f"Expected MAJOR.MINOR.PATCH version, got {version!r}")
    major, minor, patch = parts
    return f"{major}.{minor}.{int(patch) + 1}"


def _extract_pr(message: str) -> str | None:
    first_line = message.split("\n")[0].strip()
    pr_m = re.search(r"Merge pull request #(\d+)|\(#(\d+)\)", first_line)
    if not pr_m:
        return None
    return pr_m.group(1) or pr_m.group(2)


def _python_literal(value: str | None) -> str:
    if value is None:
        return "None"
    return json.dumps(value)


def bump_version(repo_root: Path, trigger_sha: str, trigger_msg: str) -> str:
    pyproject_path = repo_root / "pyproject.toml"
    plugin_path = repo_root / ".claude-plugin" / "plugin.json"
    marketplace_path = repo_root / ".claude-plugin" / "marketplace.json"
    build_info_path = repo_root / "figmaclaw" / "_build_info.py"

    pyproject = pyproject_path.read_text(encoding="utf-8")
    m = re.search(r'^version = "([^"]+)"', pyproject, re.MULTILINE)
    if not m:
        raise RuntimeError("Could not find version in pyproject.toml")
    new_version = _bump_patch(m.group(1))

    pyproject_path.write_text(
        re.sub(
            r'^(version = )"[^"]+"',
            f'\\1"{new_version}"',
            pyproject,
            flags=re.MULTILINE,
        ),
        encoding="utf-8",
    )

    plugin = json.loads(plugin_path.read_text(encoding="utf-8"))
    plugin["version"] = new_version
    plugin_path.write_text(json.dumps(plugin, indent=2) + "\n", encoding="utf-8")

    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    for plugin_entry in marketplace.get("plugins", []):
        if plugin_entry.get("name") == "figmaclaw":
            plugin_entry["version"] = new_version
    marketplace_path.write_text(json.dumps(marketplace, indent=2) + "\n", encoding="utf-8")

    build_info_path.write_text(
        "# Auto-generated by scripts/bump_version.py. Do not edit manually.\n"
        f'__version__ = "{new_version}"\n'
        f'__commit__ = "{trigger_sha}"\n'
        f"__commit_message__ = {_python_literal(trigger_msg)}\n"
        f"__pr__ = {_python_literal(_extract_pr(trigger_msg))}\n",
        encoding="utf-8",
    )

    return new_version


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--trigger-sha", default=os.environ.get("TRIGGER_SHA", ""))
    parser.add_argument("--trigger-msg", default=os.environ.get("TRIGGER_MSG", ""))
    args = parser.parse_args()

    new_version = bump_version(args.repo_root, args.trigger_sha, args.trigger_msg)
    pr = _extract_pr(args.trigger_msg)
    print(f"Bumped to {new_version} · commit={args.trigger_sha[:8]} · PR={pr}")


if __name__ == "__main__":
    main()
